/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadsRouteImport } from './routes/uploads'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AnnoncesRouteImport } from './routes/annonces'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShopSlugRouteImport } from './routes/shop.$slug'
import { Route as ApiR2UploadRouteImport } from './routes/api/r2-upload'
import { Route as AnnoncesIdRouteImport } from './routes/annonces.$id'
import { Route as DashboardListingsNewRouteImport } from './routes/dashboard.listings.new'
import { Route as DashboardListingsIdMediaRouteImport } from './routes/dashboard.listings.$id.media'
import { Route as ApiPublicHooksExpirePremiumRouteImport } from './routes/api/public/hooks/expire-premium'

const UploadsRoute = UploadsRouteImport.update({
  id: '/uploads',
  path: '/uploads',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnoncesRoute = AnnoncesRouteImport.update({
  id: '/annonces',
  path: '/annonces',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopSlugRoute = ShopSlugRouteImport.update({
  id: '/shop/$slug',
  path: '/shop/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiR2UploadRoute = ApiR2UploadRouteImport.update({
  id: '/api/r2-upload',
  path: '/api/r2-upload',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnoncesIdRoute = AnnoncesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AnnoncesRoute,
} as any)
const DashboardListingsNewRoute = DashboardListingsNewRouteImport.update({
  id: '/listings/new',
  path: '/listings/new',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardListingsIdMediaRoute =
  DashboardListingsIdMediaRouteImport.update({
    id: '/listings/$id/media',
    path: '/listings/$id/media',
    getParentRoute: () => DashboardRoute,
  } as any)
const ApiPublicHooksExpirePremiumRoute =
  ApiPublicHooksExpirePremiumRouteImport.update({
    id: '/api/public/hooks/expire-premium',
    path: '/api/public/hooks/expire-premium',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/annonces': typeof AnnoncesRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/favorites': typeof FavoritesRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/register': typeof RegisterRoute
  '/signup': typeof SignupRoute
  '/uploads': typeof UploadsRoute
  '/annonces/$id': typeof AnnoncesIdRoute
  '/api/r2-upload': typeof ApiR2UploadRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/dashboard/listings/new': typeof DashboardListingsNewRoute
  '/api/public/hooks/expire-premium': typeof ApiPublicHooksExpirePremiumRoute
  '/dashboard/listings/$id/media': typeof DashboardListingsIdMediaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/annonces': typeof AnnoncesRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/favorites': typeof FavoritesRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/register': typeof RegisterRoute
  '/signup': typeof SignupRoute
  '/uploads': typeof UploadsRoute
  '/annonces/$id': typeof AnnoncesIdRoute
  '/api/r2-upload': typeof ApiR2UploadRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/dashboard/listings/new': typeof DashboardListingsNewRoute
  '/api/public/hooks/expire-premium': typeof ApiPublicHooksExpirePremiumRoute
  '/dashboard/listings/$id/media': typeof DashboardListingsIdMediaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/annonces': typeof AnnoncesRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/favorites': typeof FavoritesRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/register': typeof RegisterRoute
  '/signup': typeof SignupRoute
  '/uploads': typeof UploadsRoute
  '/annonces/$id': typeof AnnoncesIdRoute
  '/api/r2-upload': typeof ApiR2UploadRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/dashboard/listings/new': typeof DashboardListingsNewRoute
  '/api/public/hooks/expire-premium': typeof ApiPublicHooksExpirePremiumRoute
  '/dashboard/listings/$id/media': typeof DashboardListingsIdMediaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/annonces'
    | '/dashboard'
    | '/favorites'
    | '/login'
    | '/messages'
    | '/register'
    | '/signup'
    | '/uploads'
    | '/annonces/$id'
    | '/api/r2-upload'
    | '/shop/$slug'
    | '/dashboard/listings/new'
    | '/api/public/hooks/expire-premium'
    | '/dashboard/listings/$id/media'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/annonces'
    | '/dashboard'
    | '/favorites'
    | '/login'
    | '/messages'
    | '/register'
    | '/signup'
    | '/uploads'
    | '/annonces/$id'
    | '/api/r2-upload'
    | '/shop/$slug'
    | '/dashboard/listings/new'
    | '/api/public/hooks/expire-premium'
    | '/dashboard/listings/$id/media'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/annonces'
    | '/dashboard'
    | '/favorites'
    | '/login'
    | '/messages'
    | '/register'
    | '/signup'
    | '/uploads'
    | '/annonces/$id'
    | '/api/r2-upload'
    | '/shop/$slug'
    | '/dashboard/listings/new'
    | '/api/public/hooks/expire-premium'
    | '/dashboard/listings/$id/media'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AnnoncesRoute: typeof AnnoncesRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  FavoritesRoute: typeof FavoritesRoute
  LoginRoute: typeof LoginRoute
  MessagesRoute: typeof MessagesRoute
  RegisterRoute: typeof RegisterRoute
  SignupRoute: typeof SignupRoute
  UploadsRoute: typeof UploadsRoute
  ApiR2UploadRoute: typeof ApiR2UploadRoute
  ShopSlugRoute: typeof ShopSlugRoute
  ApiPublicHooksExpirePremiumRoute: typeof ApiPublicHooksExpirePremiumRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/uploads': {
      id: '/uploads'
      path: '/uploads'
      fullPath: '/uploads'
      preLoaderRoute: typeof UploadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/annonces': {
      id: '/annonces'
      path: '/annonces'
      fullPath: '/annonces'
      preLoaderRoute: typeof AnnoncesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/$slug': {
      id: '/shop/$slug'
      path: '/shop/$slug'
      fullPath: '/shop/$slug'
      preLoaderRoute: typeof ShopSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/r2-upload': {
      id: '/api/r2-upload'
      path: '/api/r2-upload'
      fullPath: '/api/r2-upload'
      preLoaderRoute: typeof ApiR2UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/annonces/$id': {
      id: '/annonces/$id'
      path: '/$id'
      fullPath: '/annonces/$id'
      preLoaderRoute: typeof AnnoncesIdRouteImport
      parentRoute: typeof AnnoncesRoute
    }
    '/dashboard/listings/new': {
      id: '/dashboard/listings/new'
      path: '/listings/new'
      fullPath: '/dashboard/listings/new'
      preLoaderRoute: typeof DashboardListingsNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/listings/$id/media': {
      id: '/dashboard/listings/$id/media'
      path: '/listings/$id/media'
      fullPath: '/dashboard/listings/$id/media'
      preLoaderRoute: typeof DashboardListingsIdMediaRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/public/hooks/expire-premium': {
      id: '/api/public/hooks/expire-premium'
      path: '/api/public/hooks/expire-premium'
      fullPath: '/api/public/hooks/expire-premium'
      preLoaderRoute: typeof ApiPublicHooksExpirePremiumRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AnnoncesRouteChildren {
  AnnoncesIdRoute: typeof AnnoncesIdRoute
}

const AnnoncesRouteChildren: AnnoncesRouteChildren = {
  AnnoncesIdRoute: AnnoncesIdRoute,
}

const AnnoncesRouteWithChildren = AnnoncesRoute._addFileChildren(
  AnnoncesRouteChildren,
)

interface DashboardRouteChildren {
  DashboardListingsNewRoute: typeof DashboardListingsNewRoute
  DashboardListingsIdMediaRoute: typeof DashboardListingsIdMediaRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardListingsNewRoute: DashboardListingsNewRoute,
  DashboardListingsIdMediaRoute: DashboardListingsIdMediaRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AnnoncesRoute: AnnoncesRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  FavoritesRoute: FavoritesRoute,
  LoginRoute: LoginRoute,
  MessagesRoute: MessagesRoute,
  RegisterRoute: RegisterRoute,
  SignupRoute: SignupRoute,
  UploadsRoute: UploadsRoute,
  ApiR2UploadRoute: ApiR2UploadRoute,
  ShopSlugRoute: ShopSlugRoute,
  ApiPublicHooksExpirePremiumRoute: ApiPublicHooksExpirePremiumRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
